using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

[Serializable]
public class DataSchema
{
    public string key;
    public List<DataSchemaField> fields;
}

[Serializable]
public class DataSchemaField
{
    public string name;
    public string type;
    public string summary;
    public string csvName;

    public string GetCsvName()
    {
        return string.IsNullOrWhiteSpace(csvName) ? name : csvName;
    }
}

public static class DataSchemaUtility
{
    private static readonly HashSet<string> SupportedTypes = new()
    {
        "string",
        "bool",
        "byte",
        "sbyte",
        "short",
        "ushort",
        "int",
        "uint",
        "long",
        "ulong",
        "float",
        "double"
    };

    public static bool TryLoad(string schemaPath, out DataSchema schema)
    {
        schema = null;

        try
        {
            string json = File.ReadAllText(schemaPath, Encoding.UTF8);
            schema = JsonUtility.FromJson<DataSchema>(json);
        }
        catch (Exception exception)
        {
            Debug.LogError($"Failed to read schema.\n{schemaPath}\n{exception}");
            return false;
        }

        if (schema == null)
        {
            Debug.LogError($"Failed to parse schema.\n{schemaPath}");
            return false;
        }

        if (string.IsNullOrWhiteSpace(schema.key))
        {
            Debug.LogError($"Schema key is empty.\n{schemaPath}");
            return false;
        }

        if (schema.fields == null || schema.fields.Count == 0)
        {
            Debug.LogError($"Schema fields are empty.\n{schemaPath}");
            return false;
        }

        bool hasKey = false;
        HashSet<string> fieldNames = new();

        foreach (DataSchemaField field in schema.fields)
        {
            if (field == null || string.IsNullOrWhiteSpace(field.name))
            {
                Debug.LogError($"Schema field name is empty.\n{schemaPath}");
                return false;
            }

            if (!fieldNames.Add(field.name))
            {
                Debug.LogError($"Duplicated schema field name. field: {field.name}\n{schemaPath}");
                return false;
            }

            string normalizedType = NormalizeType(field.type);
            if (!SupportedTypes.Contains(normalizedType))
            {
                Debug.LogError($"Unsupported schema type. field: {field.name}, type: {field.type}\n{schemaPath}");
                return false;
            }

            if (field.name == schema.key)
                hasKey = true;
        }

        if (!hasKey)
        {
            Debug.LogError($"Schema key field is missing. key: {schema.key}\n{schemaPath}");
            return false;
        }

        return true;
    }

    public static string NormalizeType(string type)
    {
        if (string.IsNullOrWhiteSpace(type))
            return string.Empty;

        return type.Trim().ToLowerInvariant();
    }

    public static DataSchemaField GetKeyField(DataSchema schema)
    {
        foreach (DataSchemaField field in schema.fields)
        {
            if (field.name == schema.key)
                return field;
        }

        return null;
    }

    public static string ToCSharpType(string type)
    {
        return NormalizeType(type);
    }
}

public static class DataClassGenerator
{
    private const string SchemaDirectory = "Assets/CSV";
    private const string DataDirectory = "Assets/Scripts/Data";
    private const string DataManagerPath = "Assets/Scripts/Manager/DataManager.cs";
    private const string InitializeStartMarker = "        // <auto-generated data initialize>";
    private const string InitializeEndMarker = "        // </auto-generated data initialize>";

    [MenuItem("Tools/Generate data")]
    public static void Generate()
    {
        if (!Directory.Exists(SchemaDirectory))
        {
            Debug.LogError($"Schema folder not found.\n{SchemaDirectory}");
            return;
        }

        string[] schemaPaths = Directory.GetFiles(SchemaDirectory, "*.schema.json", SearchOption.TopDirectoryOnly);
        Array.Sort(schemaPaths);

        if (schemaPaths.Length == 0)
        {
            Debug.LogError($"Schema files not found.\n{SchemaDirectory}");
            return;
        }

        Directory.CreateDirectory(DataDirectory);
        int generatedCount = 0;
        List<string> dataClassNames = new();

        foreach (string schemaPath in schemaPaths)
        {
            if (!DataSchemaUtility.TryLoad(schemaPath, out DataSchema schema))
                continue;

            string baseName = Path.GetFileNameWithoutExtension(Path.GetFileNameWithoutExtension(schemaPath));
            string rowClassName = GetRowClassName(baseName);
            string dataClassName = GetDataClassName(baseName);

            File.WriteAllText(
                Path.Combine(DataDirectory, $"{rowClassName}.cs"),
                GenerateRowClass(rowClassName, schema),
                Encoding.UTF8);

            File.WriteAllText(
                Path.Combine(DataDirectory, $"{dataClassName}.cs"),
                GenerateDataClass(rowClassName, dataClassName, baseName, schema),
                Encoding.UTF8);

            dataClassNames.Add(dataClassName);
            generatedCount++;
            Debug.Log($"{schemaPath} -> {rowClassName}.cs, {dataClassName}.cs generated.");
        }

        UpdateDataManager(dataClassNames);

        AssetDatabase.Refresh();
        Debug.Log($"{generatedCount} schema files generated data classes.");
    }

    private static string GetRowClassName(string baseName)
    {
        if (baseName.EndsWith("Data", StringComparison.Ordinal))
            return baseName.Substring(0, baseName.Length - "Data".Length);

        return baseName;
    }

    private static string GetDataClassName(string baseName)
    {
        if (baseName.EndsWith("Data", StringComparison.Ordinal))
            return baseName;

        return $"{baseName}Data";
    }

    private static string GenerateRowClass(string rowClassName, DataSchema schema)
    {
        StringBuilder builder = new();
        builder.AppendLine("using System;");
        builder.AppendLine();
        builder.AppendLine("[Serializable]");
        builder.AppendLine($"public partial class {rowClassName}");
        builder.AppendLine("{");

        foreach (DataSchemaField field in schema.fields)
        {
            string summary = string.IsNullOrWhiteSpace(field.summary) ? field.name : field.summary;

            builder.AppendLine("    /// <summary>");
            builder.AppendLine($"    /// {EscapeXml(summary)}");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public {DataSchemaUtility.ToCSharpType(field.type)} {field.name};");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GenerateDataClass(string rowClassName, string dataClassName, string jsonName, DataSchema schema)
    {
        DataSchemaField keyField = DataSchemaUtility.GetKeyField(schema);
        string keyType = DataSchemaUtility.ToCSharpType(keyField.type);

        StringBuilder builder = new();
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using UnityEngine;");
        builder.AppendLine("using UnityEngine.AddressableAssets;");
        builder.AppendLine("using UnityEngine.ResourceManagement.AsyncOperations;");
        builder.AppendLine();
        builder.AppendLine("[Serializable]");
        builder.AppendLine($"public class {rowClassName}Database");
        builder.AppendLine("{");
        builder.AppendLine($"    public List<{rowClassName}> rows;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("// Load data file and store rows in a dictionary.");
        builder.AppendLine($"public partial class {dataClassName} : IData");
        builder.AppendLine("{");
        builder.AppendLine($"    public Dictionary<{keyType}, {rowClassName}> Datas {{ get; private set; }} = null;");
        builder.AppendLine();
        builder.AppendLine($"    private const string ADDRESS = \"{jsonName}.json\";");
        builder.AppendLine("    private AsyncOperationHandle<TextAsset> _handle;");
        builder.AppendLine();
        builder.AppendLine("    public async Task Initialize()");
        builder.AppendLine("    {");
        builder.AppendLine("        await Load();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public void Release()");
        builder.AppendLine("    {");
        builder.AppendLine("        if (_handle.IsValid())");
        builder.AppendLine("        {");
        builder.AppendLine("            Addressables.Release(_handle);");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private async Task Load()");
        builder.AppendLine("    {");
        builder.AppendLine("        Release();");
        builder.AppendLine();
        builder.AppendLine("        _handle = Addressables.LoadAssetAsync<TextAsset>(ADDRESS);");
        builder.AppendLine("        TextAsset jsonFile = await _handle.Task;");
        builder.AppendLine();
        builder.AppendLine("        if (jsonFile == null)");
        builder.AppendLine("        {");
        builder.AppendLine($"            Debug.LogError(\"{jsonName}.json not found\");");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        {rowClassName}Database database = JsonUtility.FromJson<{rowClassName}Database>(jsonFile.text);");
        builder.AppendLine();
        builder.AppendLine("        Datas ??= new();");
        builder.AppendLine("        Datas.Clear();");
        builder.AppendLine();
        builder.AppendLine($"        List<{rowClassName}> rows = database.rows;");
        builder.AppendLine();
        builder.AppendLine("        if (rows == null)");
        builder.AppendLine("        {");
        builder.AppendLine($"            Debug.LogError(\"{jsonName}.json data not found\");");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        foreach (var row in rows)");
        builder.AppendLine("        {");
        builder.AppendLine($"            if (!Datas.ContainsKey(row.{keyField.name}))");
        builder.AppendLine("            {");
        builder.AppendLine($"                Datas.Add(row.{keyField.name}, row);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        Debug.Log($\"{Datas.Count} loaded\");");
        builder.AppendLine();
        builder.AppendLine("        SetDictionaryData();");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// Get data");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    /// <param name=\"index\">Index</param>");
        builder.AppendLine("    /// <returns></returns>");
        builder.AppendLine($"    public {rowClassName} GetData({keyType} index)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (Datas != null && Datas.TryGetValue(index, out var data))");
        builder.AppendLine("        {");
        builder.AppendLine("            return data;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return null;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void UpdateDataManager(List<string> dataClassNames)
    {
        if (!File.Exists(DataManagerPath))
        {
            Debug.LogError($"DataManager not found.\n{DataManagerPath}");
            return;
        }

        dataClassNames.Sort(StringComparer.Ordinal);

        string source = File.ReadAllText(DataManagerPath, Encoding.UTF8);
        string generatedBlock = CreateInitializeBlock(dataClassNames);

        if (source.Contains(InitializeStartMarker) && source.Contains(InitializeEndMarker))
        {
            source = ReplaceMarkedBlock(source, generatedBlock);
        }
        else
        {
            source = ReplaceInitializeBody(source, generatedBlock);
        }

        File.WriteAllText(DataManagerPath, source, Encoding.UTF8);
        Debug.Log("DataManager.Initialize generated.");
    }

    private static string CreateInitializeBlock(List<string> dataClassNames)
    {
        StringBuilder builder = new();
        builder.AppendLine(InitializeStartMarker);

        foreach (string dataClassName in dataClassNames)
        {
            builder.AppendLine($"        await AddData<{dataClassName}>();");
        }

        builder.Append(InitializeEndMarker);
        return builder.ToString();
    }

    private static string ReplaceMarkedBlock(string source, string generatedBlock)
    {
        int startIndex = source.IndexOf(InitializeStartMarker, StringComparison.Ordinal);
        int endIndex = source.IndexOf(InitializeEndMarker, StringComparison.Ordinal);

        if (startIndex < 0 || endIndex < startIndex)
            return source;

        endIndex += InitializeEndMarker.Length;
        return source.Substring(0, startIndex) + generatedBlock + source.Substring(endIndex);
    }

    private static string ReplaceInitializeBody(string source, string generatedBlock)
    {
        const string signature = "public async Task Initialize()";
        int signatureIndex = source.IndexOf(signature, StringComparison.Ordinal);

        if (signatureIndex < 0)
        {
            Debug.LogError("DataManager.Initialize method not found.");
            return source;
        }

        int openBraceIndex = source.IndexOf('{', signatureIndex);
        if (openBraceIndex < 0)
        {
            Debug.LogError("DataManager.Initialize open brace not found.");
            return source;
        }

        int closeBraceIndex = FindMatchingBrace(source, openBraceIndex);
        if (closeBraceIndex < 0)
        {
            Debug.LogError("DataManager.Initialize close brace not found.");
            return source;
        }

        string replacement = "{\r\n" + generatedBlock + "\r\n    }";
        return source.Substring(0, openBraceIndex) + replacement + source.Substring(closeBraceIndex + 1);
    }

    private static int FindMatchingBrace(string source, int openBraceIndex)
    {
        int depth = 0;

        for (int i = openBraceIndex; i < source.Length; i++)
        {
            if (source[i] == '{')
                depth++;
            else if (source[i] == '}')
                depth--;

            if (depth == 0)
                return i;
        }

        return -1;
    }

    private static string EscapeXml(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
